name: API Tests

on:
  push:
    branches: [ main ]

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Tests
        run: newman run Restful-Booker.postman_collection.json -r cli,htmlextra --reporter-htmlextra-export report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html
